export const books = [
    {
      id: 1,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      category: "Fiction",
      imageLink: "https://m.media-amazon.com/images/I/81YPgi4vpDL.jpg",
      language: "English",
      pages: 324,
      date: "1960-07-11",
      year: 1960,
      rating: 4.8
    },
    {
      id: 2,
      title: "1984",
      author: "George Orwell",
      category: "Dystopian",
      imageLink: "https://books.google.co.in/books/publisher/content?id=0vQCEAAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U0YCgL0_QjFBTuovIB_4v-3h9DGDg&w=1280",
      language: "English",
      pages: 328,
      date: "1949-06-08",
      year: 1949,
      rating: 4.7
    },
    {
      id: 3,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      category: "Romance",
      imageLink: "https://m.media-amazon.com/images/I/91HHqVTAJQL.jpg",
      language: "English",
      pages: 279,
      date: "1813-01-28",
      year: 1813,
      rating: 4.6
    },
    {
      id: 4,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      category: "Classic",
      imageLink: "https://books.google.co.in/books/publisher/content?id=WpD_DAAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2smY1XG0tjSZpqcsPWGRs18i-NFg&w=1280",
      language: "English",
      pages: 180,
      date: "1925-04-10",
      year: 1925,
      rating: 4.4
    },
    {
      id: 5,
      title: "Moby Dick",
      author: "Herman Melville",
      category: "Adventure",
      imageLink: "https://books.google.co.in/books/content?id=cyokAAAAMAAJ&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2S75qdojGvk4m24fXaVbxGS0IsEg&w=1280",
      language: "English",
      pages: 635,
      date: "1851-10-18",
      year: 1851,
      rating: 4.0
    },
    {
      id: 6,
      title: "War and Peace",
      author: "Leo Tolstoy",
      category: "Historical",
      imageLink: "https://books.google.co.in/books/content?id=tKf-ovCArycC&pg=PP1&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2kDCczzsmKcWk-KIwBk125r1BB1Q&w=1280",
      language: "Russian",
      pages: 1225,
      date: "1869-01-01",
      year: 1869,
      rating: 4.5
    },
    {
      id: 7,
      title: "Crime and Punishment",
      author: "Fyodor Dostoevsky",
      category: "Psychological",
      imageLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkTTt8k4UtutYY2HO75AB2V_tstMC-W39Dig&s",
      language: "Russian",
      pages: 671,
      date: "1866-01-01",
      year: 1866,
      rating: 4.6
    },
    {
      id: 8,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      category: "Coming-of-Age",
      imageLink: "https://m.media-amazon.com/images/I/81OthjkJBuL.jpg",
      language: "English",
      pages: 277,
      date: "1951-07-16",
      year: 1951,
      rating: 4.3
    },
    {
      id: 9,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      category: "Fantasy",
      imageLink: "https://m.media-amazon.com/images/I/91b0C2YNSrL.jpg",
      language: "English",
      pages: 310,
      date: "1937-09-21",
      year: 1937,
      rating: 4.8
    },
    {
      id: 10,
      title: "The Odyssey",
      author: "Homer",
      category: "Epic",
      imageLink: "https://m.media-amazon.com/images/I/81g0AATkO9L._AC_UF1000,1000_QL80_.jpg",
      language: "Greek",
      pages: 541,
      date: "800-01-01",
      year: -800,
      rating: 4.7
    },
    {
      id: 11,
      title: "The Alchemist",
      author: "Paulo Coelho",
      category: "Adventure",
      imageLink: "https://m.media-amazon.com/images/I/71aFt4+OTOL.jpg",
      language: "Portuguese",
      pages: 197,
      date: "1988-04-01",
      year: 1988,
      rating: 4.6
    },
    {
      id: 12,
      title: "Frankenstein",
      author: "Mary Shelley",
      category: "Horror",
      imageLink: "https://m.media-amazon.com/images/I/71c1LRLBTBL.jpg",
      language: "English",
      pages: 280,
      date: "1818-01-01",
      year: 1818,
      rating: 4.3
    },
    {
      id: 13,
      title: "Dracula",
      author: "Bram Stoker",
      category: "Horror",
      imageLink: "https://m.media-amazon.com/images/I/81WcnNQ-TBL.jpg",
      language: "English",
      pages: 418,
      date: "1897-05-26",
      year: 1897,
      rating: 4.5
    },
    {
      id: 14,
      title: "Jane Eyre",
      author: "Charlotte Bronte",
      category: "Classic",
      imageLink: "https://m.media-amazon.com/images/I/61N-UOA0alL._UF1000,1000_QL80_.jpg",
      language: "English",
      pages: 500,
      date: "1847-10-16",
      year: 1847,
      rating: 4.7
    },
    {
      id: 15,
      title: "Wuthering Heights",
      author: "Emily Bronte",
      category: "Romance",
      imageLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4jAgJC8h_mdnvk4qT6JEWvA2tNXunsGSz5w&s",
      language: "English",
      pages: 416,
      date: "1847-12-01",
      year: 1847,
      rating: 4.4
    },
    {
      id: 16,
      title: "The Picture of Dorian Gray",
      author: "Oscar Wilde",
      category: "Philosophical",
      imageLink: "https://m.media-amazon.com/images/I/81eB+7+CkUL.jpg",
      language: "English",
      pages: 254,
      date: "1890-06-20",
      year: 1890,
      rating: 4.5
    },
    {
      id: 17,
      title: "Brave New World",
      author: "Aldous Huxley",
      category: "Dystopian",
      imageLink: "https://m.media-amazon.com/images/I/91D4YvdC0dL._AC_UF1000,1000_QL80_.jpg",
      language: "English",
      pages: 268,
      date: "1932-01-01",
      year: 1932,
      rating: 4.6
    },
    {
      id: 18,
      title: "The Brothers Karamazov",
      author: "Fyodor Dostoevsky",
      category: "Philosophical",
      imageLink: "https://m.media-amazon.com/images/I/71OZJsgZzQL._AC_UF1000,1000_QL80_.jpg",
      language: "Russian",
      pages: 824,
      date: "1880-01-01",
      year: 1880,
      rating: 4.7
    },
    {
      id: 19,
      title: "The Divine Comedy",
      author: "Dante Alighieri",
      category: "Epic",
      imageLink: "https://m.media-amazon.com/images/I/51i-9SGWr-L._AC_UF1000,1000_QL80_.jpg",
      language: "Italian",
      pages: 798,
      date: "1320-01-01",
      year: 1320,
      rating: 4.9
    },
    {
      id: 20,
      title: "The Metamorphosis",
      author: "Franz Kafka",
      category: "Surreal",
      imageLink: "https://m.media-amazon.com/images/I/81QOkf8RSIL._AC_UF1000,1000_QL80_.jpg ",
      language: "German",
      pages: 201,
      date: "1915-01-01",
      year: 1915,
      rating: 4.2
    },
    {
        id: 21,
        title: "Don Quixote",
        author: "Miguel de Cervantes",
        category: "Classic",
        imageLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPKfM12nIqGnqIkFJQeFMgw2R8JNbK8qz8Pg&s",
        language: "Spanish",
        pages: 992,
        date: "1605-01-16",
        year: 1605,
        rating: 4.8
      },
      {
          id: 22,
          title: "Les Misérables",
          author: "Victor Hugo",
          category: "Fiction", // Changed to Fiction
          imageLink: "https://m.media-amazon.com/images/I/91p594CxSpL.jpg",
          language: "French",
          pages: 1463,
          date: "1862-01-01",
          year: 1862,
          rating: 4.7,
        },
        {
          id: 23,
          title: "Anna Karenina",
          author: "Leo Tolstoy",
          category: "Fiction", // Changed to Fiction
          imageLink: "https://m.media-amazon.com/images/I/71O3PTUA3vL._AC_UF1000,1000_QL80_.jpg",
          language: "Russian",
          pages: 864,
          date: "1877-01-01",
          year: 1877,
          rating: 4.6,
        },
        {
          id: 24,
          title: "The Old Man and the Sea",
          author: "Ernest Hemingway",
          category: "Fiction", // Changed to Fiction
          imageLink: "https://m.media-amazon.com/images/I/71+rqbp57dL.jpg",
          language: "English",
          pages: 127,
          date: "1952-09-01",
          year: 1952,
          rating: 4.4,
        },
        {
          id: 25,
          title: "Madame Bovary",
          author: "Gustave Flaubert",
          category: "Fiction", // Changed to Fiction
          imageLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQePeLB19D27XaVGtitTMQykUJOXrJ2zygliA&s",
          language: "French",
          pages: 377,
          date: "1857-01-01",
          year: 1857,
          rating: 4.3,
        },
        {
          id: 26,
          title: "The Road",
          author: "Cormac McCarthy",
          category: "Sci-Fi", // Changed to Sci-Fi
          imageLink: "https://m.media-amazon.com/images/I/51M7XGLQTBL._AC_UF1000,1000_QL80_.jpg",
          language: "English",
          pages: 287,
          date: "2006-09-26",
          year: 2006,
          rating: 4.5,
        },
        {
          id: 27,
          title: "One Hundred Years of Solitude",
          author: "Gabriel García Márquez",
          category: "Fiction", // Changed to Fiction
          imageLink: "https://m.media-amazon.com/images/I/81oAEEwxBWL.jpg",
          language: "Spanish",
          pages: 417,
          date: "1967-05-30",
          year: 1967,
          rating: 4.7,
        },
        {
          id: 28,
          title: "The Kite Runner",
          author: "Khaled Hosseini",
          category: "Fiction", // Changed to Fiction
          imageLink: "https://m.media-amazon.com/images/I/81IzbD2IiIL._AC_UF1000,1000_QL80_.jpg",
          language: "English",
          pages: 371,
          date: "2003-05-29",
          year: 2003,
          rating: 4.8,
        },
        {
          id: 29,
          title: "Slaughterhouse-Five",
          author: "Kurt Vonnegut",
          category: "Sci-Fi", // Changed to Sci-Fi
          imageLink: "https://m.media-amazon.com/images/I/51jLxTxTnyL.jpg",
          language: "English",
          pages: 275,
          date: "1969-03-31",
          year: 1969,
          rating: 4.6,
        },
        {
          id: 30,
          title: "The Grapes of Wrath",
          author: "John Steinbeck",
          category: "Non-Fiction", // Changed to Non-Fiction
          imageLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtVcSQFGYirxzyD1hVL2L1S4wneoflwRG1Bg&s",
          language: "English",
          pages: 464,
          date: "1939-04-14",
          year: 1939,
          rating: 4.7,
        },
      ];
